### PR TITLE
fix: Taro 3.0.x persist problem

### PR DESCRIPTION
**Pull request by tian-zhihui**
Please refer to: https://github.com/NervJS/taro/issues/6548.
Tested on tarojs 3.0.15.

### CODE REVIEW

**Comment by fwh1990** [comment]
The fix logic is ok, would you please focus push commit again to remove the changes from *.json files, to test in development , we just run script `yarn && yarn bootstrap` to setup and then run `yarn test` to test.

**Comment by tian-zhihui** [comment]
@fwh1990 Thanks. Changes in *.json files removed. Could you please confirm it again?

**Comment by fwh1990** [comment]
I'll check it out and publish new version later. Thank you for your effort

**Comment by fwh1990** [comment]
Since Taro going to support React-Native, the api `getStorageSync` may be replaced by `getStorage` again, it depends on what TARO says:
https://github.com/NervJS/taro/pull/8093
https://taro-docs.jd.com/taro/docs/apis/storage/getStorageSync#api-%E6%94%AF%E6%8C%81%E5%BA%A6

**Comment by fwh1990** [comment]
You don't need to submit anything, I just want to tell you the truth.

**Comment by fwh1990** [comment]
And now I have a question? What's the difference between `getStorage()` and `Promise.resolve().then()`, they are both asynchronized.

**Comment by tian-zhihui** [comment]
> Since Taro going to support React-Native, the api `getStorageSync` may be replaced by `getStorage` again, it depends on what TARO says:
> [NervJS/taro#8093](https://github.com/NervJS/taro/pull/8093)
> https://taro-docs.jd.com/taro/docs/apis/storage/getStorageSync#api-%E6%94%AF%E6%8C%81%E5%BA%A6

Thank you for the information.
I just followed the answer from this issue: https://github.com/NervJS/taro/issues/6548#issuecomment-717896033.
After change getStorage to getStorageSync, I can use PersistGate on Taro 3.0.x again on wechat devtools, but the issue is still exists on the real machine.
Maybe I should find out the real reason for https://github.com/redux-model/redux-model/issues/22#issuecomment-733421841.

**Comment by tian-zhihui** [comment]
I finally figured out the reason for #22 . We can solve this issue without change any code of redux-model.
As this comment (https://github.com/NervJS/taro/issues/6548#issuecomment-717896033) said, we need to make sure there is a page instance to be render during loading like below: 
```xml
<Provider store={store}>
  <PersistGate loading={props.children}>{props.children}</PersistGate>
</Provider>
````
But I think maybe add some code like set loading to props.children before the below line when loading is null maybe a better choice.
https://github.com/redux-model/redux-model/blob/83a8456ae18bf0a5c95e237b87db63bab8d98ff9/packages/taro/src/components/PersistGate.tsx#L51

**Comment by fwh1990** [comment]
We should keep loading component to make sure redux data has been fetched already before page instance. Therefore, put `PersistGate` into home page will be the only solution for now.

In other words, I will revert the commit you submitted hours ago, is't right?

**Comment by tian-zhihui** [comment]
Sure. please revert my commit.

**Comment by fwh1990** [comment]
Ok, I will edit the document to guide user how to place the PersistGate.

**Comment by fwh1990** [comment]
By the way, Chinese or Japanese?

**Comment by tian-zhihui** [comment]
同胞

**Comment by fwh1990** [comment]
Once user visit the mini-program with route path, the target page will bypass home page which contains PersistGate. It's unexpected, any way to avoid this behavior?

**Comment by lzhlo** [comment]
说中文吧 楼上老铁

**Pull request merged**
